spring:
  application:
    name: auth-service
  docker:
    compose:
      enabled: false
  jackson:
    default-property-inclusion: non_null
  threads:
    virtual:
      enabled: true

  config:
    import:
      # Common base-core configs
      - optional:classpath:application-core-observability.yml
      - optional:classpath:application-core-logging.yml
      - optional:classpath:application-core-resilience.yml
      - optional:classpath:application-core-cipher.yml
      # Service-specific configs
      - classpath:application-db.yml
      - classpath:application-security.yml
      - classpath:application-cache.yml

server:
  port: 8081
