package com.ntt.authservice.shared.security

import com.ntt.basecore.autoconfigure.security.entity.EndpointSecurityRuleEntity
import com.ntt.basecore.autoconfigure.security.repository.EndpointSecurityRuleRepository
import org.slf4j.LoggerFactory
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

/**
 * Internal API for service-to-service security rule bulk fetch.
 *
 * Used as fallback when Redis is unavailable:
 * DynamicAuthorizationManager (other services) → GET /api/internal/security-rules → DB query
 *
 * Authentication: Requires ROLE_SERVICE + SCOPE_internal (handled by ServiceAuthFilter).
 */
@RestController
@RequestMapping("/internal/security-rules")
class InternalSecurityRuleController(
    private val ruleRepository: EndpointSecurityRuleRepository
) {
    private val log = LoggerFactory.getLogger(InternalSecurityRuleController::class.java)

    /**
     * Bulk fetch all active endpoint security rules, sorted by sort_order.
     * Returns JSON array of EndpointSecurityRuleDTO.
     */
    @GetMapping
    fun getAllActiveRules(): ResponseEntity<List<EndpointSecurityRuleDTO>> {
        val rules = ruleRepository.findAllActiveOrderBySortOrder()
        val dtos = rules.map { it.toDTO() }
        log.info("Internal API: returning {} active security rules", dtos.size)
        return ResponseEntity.ok(dtos)
    }
}

/**
 * DTO for internal API response — includes menu-auth fields.
 */
data class EndpointSecurityRuleDTO(
    val id: Long,
    val urlPattern: String,
    val patternType: String,
    val httpMethod: String?,
    val accessType: String,
    val requiredRoles: List<String>?,
    val requiredPerms: List<String>?,
    val domainScope: String?,
    val sortOrder: Int,
    val sourceMenuCode: String?,
    val autoGenerated: Boolean
)

fun EndpointSecurityRuleEntity.toDTO() = EndpointSecurityRuleDTO(
    id = id!!,
    urlPattern = urlPattern,
    patternType = patternType,
    httpMethod = httpMethod,
    accessType = accessType,
    requiredRoles = requiredRoles?.toList(),
    requiredPerms = requiredPerms?.toList(),
    domainScope = domainScope,
    sortOrder = sortOrder,
    sourceMenuCode = sourceMenuCode,
    autoGenerated = autoGenerated
)
