package com.ntt.authservice.shared.security

import com.fasterxml.jackson.databind.ObjectMapper
import com.ntt.basecore.autoconfigure.security.DynamicAuthorizationManager
import com.ntt.basecore.autoconfigure.security.repository.EndpointSecurityRuleRepository
import org.slf4j.LoggerFactory
import org.springframework.data.redis.core.StringRedisTemplate
import org.springframework.stereotype.Component

/**
 * Publishes all active endpoint security rules to Redis.
 *
 * Redis key: auth:endpoint-rules (single JSON array, sorted by sort_order)
 * Redis channel: auth-service:security-rules:changed (pub/sub notification)
 *
 * Called after every rule upsert/delete to keep Redis in sync.
 */
@Component
class MenuRuleRedisPublisher(
    private val ruleRepository: EndpointSecurityRuleRepository,
    private val redisTemplate: StringRedisTemplate?,
    private val objectMapper: ObjectMapper,
    private val dynamicAuthorizationManager: DynamicAuthorizationManager
) {
    private val log = LoggerFactory.getLogger(MenuRuleRedisPublisher::class.java)

    companion object {
        const val REDIS_KEY = "auth:endpoint-rules"
    }

    /**
     * Query all active rules from DB, serialize to JSON, publish to Redis.
     * Then notify all service instances via pub/sub.
     */
    fun publishAllRules() {
        try {
            val rules = ruleRepository.findAllActiveOrderBySortOrder()
            val rulesJson = objectMapper.writeValueAsString(rules.map { rule ->
                mapOf(
                    "id" to rule.id,
                    "urlPattern" to rule.urlPattern,
                    "patternType" to rule.patternType,
                    "httpMethod" to rule.httpMethod,
                    "accessType" to rule.accessType,
                    "requiredRoles" to rule.requiredRoles?.toList(),
                    "requiredPerms" to rule.requiredPerms?.toList(),
                    "domainScope" to rule.domainScope,
                    "sortOrder" to rule.sortOrder,
                    "sourceMenuCode" to rule.sourceMenuCode,
                    "autoGenerated" to rule.autoGenerated
                )
            })

            // Write to Redis key
            redisTemplate?.opsForValue()?.set(REDIS_KEY, rulesJson)
            log.info("Published {} active rules to Redis key: {}", rules.size, REDIS_KEY)

            // Notify all listeners to evict L1 cache
            redisTemplate?.convertAndSend(
                SecurityRuleCacheConfig.CHANNEL,
                """{"action":"MENU_SYNC","timestamp":"${java.time.Instant.now()}"}"""
            )

            // Also evict local cache immediately
            dynamicAuthorizationManager.evictCache()
        } catch (ex: Exception) {
            log.error("Failed to publish rules to Redis: {}", ex.message, ex)
            // Non-blocking — DB is the master source, Redis is L2 cache
        }
    }
}
