package com.ntt.authservice.shared.security

import com.ntt.authservice.shared.security.event.MenuPermissionChangedEvent
import com.ntt.authservice.shared.security.event.MenuPermissionPayload
import com.ntt.basecore.autoconfigure.security.entity.EndpointSecurityRuleEntity
import com.ntt.basecore.autoconfigure.security.repository.EndpointSecurityRuleRepository
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Component

/**
 * Maps a Kafka MenuPermissionChangedEvent to endpoint_security_rules.
 *
 * Guards:
 * - G1: Skip if assignedRoles is empty (prevent lockout — FR-003)
 * - G3: Skip if path is null or doesn't start with /api/ (FR-014)
 *
 * Rule mapping:
 * - url_pattern = menuPath + "/[wildcard]"
 * - access_type = HAS_AUTHORITY
 * - required_perms = permissions.map { "menu:{menuCode}:{it.code}" }
 * - source_menu_code = menuCode
 * - auto_generated = true
 */
@Component
class MenuSecurityRuleMapper(
    private val ruleRepository: EndpointSecurityRuleRepository
) {
    private val log = LoggerFactory.getLogger(MenuSecurityRuleMapper::class.java)

    /**
     * Process a menu permission event: upsert or soft-delete rules.
     *
     * @return true if a rule was modified, false if skipped
     */
    fun processEvent(event: MenuPermissionChangedEvent): Boolean {
        val payload = event.payload
        val action = payload.action.uppercase()

        return when (action) {
            "CREATED", "UPDATED" -> upsertRule(payload)
            "DELETED" -> softDeleteRule(payload.menuCode)
            else -> {
                log.warn("Unknown menu event action: {}", action)
                false
            }
        }
    }

    private fun upsertRule(payload: MenuPermissionPayload): Boolean {
        // Guard G1: Skip if no roles assigned (prevent lockout)
        if (payload.assignedRoles.isEmpty()) {
            log.info("Guard G1: No roles assigned for menuCode={}, skipping rule generation", payload.menuCode)
            // If rule already exists, soft-delete it
            softDeleteRule(payload.menuCode)
            return false
        }

        // Guard G3: Skip if path is null or doesn't start with /api/
        if (payload.menuPath.isNullOrBlank() || !payload.menuPath.startsWith("/api/")) {
            log.info("Guard G3: Path '{}' invalid for menuCode={}, skipping", payload.menuPath, payload.menuCode)
            return false
        }

        // Build required permissions: menu:{menuCode}:{permCode}
        val requiredPerms = payload.permissions.map { "menu:${payload.menuCode}:${it.code}" }
        if (requiredPerms.isEmpty()) {
            log.info("No permissions defined for menuCode={}, skipping rule", payload.menuCode)
            return false
        }

        // Build required roles from assigned roles
        val requiredRoles = payload.assignedRoles.map { it.roleName }.filter { it.isNotBlank() }

        // Upsert: find existing by source_menu_code or create new
        val existing = ruleRepository.findBySourceMenuCode(payload.menuCode)

        val rule = existing ?: EndpointSecurityRuleEntity().apply {
            createdBy = "MENU_SYNC"
        }

        rule.apply {
            urlPattern = payload.menuPath + "/**"
            patternType = "ANT"
            httpMethod = null // All methods
            accessType = "HAS_AUTHORITY"
            this.requiredPerms = requiredPerms.toTypedArray()
            if (requiredRoles.isNotEmpty()) {
                this.requiredRoles = requiredRoles.toTypedArray()
            }
            domainScope = if (payload.domainId > 0) payload.domainId.toString() else null
            sortOrder = 500 // Auto-generated rules after manual rules
            isActive = true
            description = "Auto-generated from menu: ${payload.menuCode}"
            sourceMenuCode = payload.menuCode
            autoGenerated = true
            updatedBy = "MENU_SYNC"
        }

        ruleRepository.save(rule)
        log.info("Upserted security rule for menuCode={}, path={}", payload.menuCode, rule.urlPattern)
        return true
    }

    private fun softDeleteRule(menuCode: String): Boolean {
        val rule = ruleRepository.findBySourceMenuCode(menuCode) ?: return false
        rule.isActive = false
        rule.updatedBy = "MENU_SYNC"
        ruleRepository.save(rule)
        log.info("Soft-deleted security rule for menuCode={}", menuCode)
        return true
    }
}
