package com.ntt.authservice.shared.security

import com.ntt.authservice.rbac.adapter.out.persistence.repository.GroupRoleRepository
import com.ntt.authservice.rbac.adapter.out.persistence.repository.UserGroupRepository
import com.ntt.basecore.autoconfigure.security.entity.EndpointSecurityRuleEntity
import com.ntt.basecore.autoconfigure.security.repository.EndpointSecurityRuleRepository
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Component

/**
 * Data provider for menu permission computation.
 *
 * Resolves:
 * 1. User → Role mapping (from auth DB: users → user_groups → group_roles → roles)
 * 2. Role → Menu permissions (from endpoint_security_rules with source_menu_code)
 *
 * Design decision (OQ-03): auth-service computes permissions centrally.
 * Data sources:
 * - Auth DB for user-role mapping (direct access)
 * - endpoint_security_rules for menu-based rules (auto_generated=true, source_menu_code not null)
 */
@Component
class MenuPermissionDataProvider(
    private val userGroupRepository: UserGroupRepository,
    private val groupRoleRepository: GroupRoleRepository,
    private val ruleRepository: EndpointSecurityRuleRepository
) {
    private val log = LoggerFactory.getLogger(MenuPermissionDataProvider::class.java)

    /**
     * Find all userIds that have any of the given roleIds.
     * Path: role → group_roles → user_groups → userId
     *
     * @param roleIds list of role IDs to resolve
     * @return distinct set of user IDs
     */
    fun findUserIdsByRoleIds(roleIds: List<Long>): Set<Long> {
        if (roleIds.isEmpty()) return emptySet()

        // Find all groups that have any of these roles
        val groupRoles = groupRoleRepository.findAllByRoleIdInAndActiveTrue(roleIds)
        val groupIds = groupRoles.map { it.groupId }.distinct()

        if (groupIds.isEmpty()) return emptySet()

        // Find all users in these groups
        val userGroups = userGroupRepository.findAllByGroupIdInAndActiveTrue(groupIds)
        val userIds = userGroups.map { it.userId }.toSet()

        log.debug("Resolved {} users for roleIds={}", userIds.size, roleIds)
        return userIds
    }

    /**
     * Find all role IDs assigned to a user.
     * Path: userId → user_groups → group_roles → roleId
     *
     * @param userId the user to query
     * @return list of role IDs
     */
    fun findRoleIdsByUserId(userId: Long): List<Long> {
        val userGroups = userGroupRepository.findAllByUserIdAndActiveTrue(userId)
        val groupIds = userGroups.map { it.groupId }

        if (groupIds.isEmpty()) return emptyList()

        val roleIds = mutableSetOf<Long>()
        groupIds.forEach { groupId ->
            val groupRoles = groupRoleRepository.findAllByGroupIdAndActiveTrue(groupId)
            roleIds.addAll(groupRoles.map { it.roleId })
        }

        return roleIds.toList()
    }

    /**
     * Find all menu permission entries for the given role IDs.
     *
     * Extracts from auto-generated endpoint_security_rules:
     * - source_menu_code → menuCode
     * - required_perms → individual permission codes (menu:{menuCode}:{permCode})
     *
     * @param roleIds role IDs to query permissions for
     * @return list of MenuPermissionEntry
     */
    fun findMenuPermissionsByRoleIds(roleIds: List<Long>): List<MenuPermissionEntry> {
        // Get all auto-generated, active rules
        val rules = ruleRepository.findAllActiveOrderBySortOrder()
            .filter { it.autoGenerated && it.sourceMenuCode != null }

        if (rules.isEmpty()) return emptyList()

        // Extract menu permission entries from rules
        // Each rule has required_perms like ["menu:user-management:view", "menu:user-management:edit"]
        val entries = mutableListOf<MenuPermissionEntry>()

        rules.forEach { rule ->
            val menuCode = rule.sourceMenuCode ?: return@forEach
            rule.requiredPerms?.forEach { perm ->
                // Parse "menu:{menuCode}:{permCode}" format
                val parts = perm.split(":")
                if (parts.size == 3 && parts[0] == "menu") {
                    entries.add(MenuPermissionEntry(
                        menuCode = parts[1],
                        permissionCode = parts[2]
                    ))
                }
            }
        }

        return entries
    }
}
